version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network

  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle_container
    environment:
      ORACLE_PASSWORD: password
    ports:
      - "1521:1521"
    networks:
      - app-network

  h2:
    image: oscarfonts/h2
    container_name: h2_container
    ports:
      - "8082:8082" # consola web de H2
    environment:
      H2_OPTIONS: "-ifNotExists"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

